### ISSUE TITLE
[Feature] TAX change protection

### ISSUE THREAD

**Issue by AdamB2023** [tsarbuig/WalletHunter#1]
Similar to LP removal, TAX change protection could be added.
This can be accomplished with the following variables:
1. `TAX_CHECK_DURING_TRADE` - `true` or `false`; will enable or disable feature
2. `MAX_SELL_TAX_DURING_IN_TRADE` - `x%`; if sell tax will reach x% after entering trade, WH will attempt to sell
3. `MAX_SELL_TAX_INCREASE_DURING_IN_TRADE` - `x%`; if sell tax change more than x% after entering trade, WH will attempt to sell

**Comment by tsarbuig** [comment]
but it already exist ? 

![image](https://user-images.githubusercontent.com/70858574/215622660-1a4d4d1e-4a35-47ff-abb9-bbb4cb3fa943.png)

and Antirug has an automatic Tax increase detection : if SELL tax becomes > 60% it will sell automatically

**Comment by AdamB2023** [comment]
Oh! I was not aware that the TAX is also checked during trade.
I will put my eyes on it during back testing.
