### ISSUE TITLE
New Feature Request - Prevent Sale if SELL TAX Too High

### ISSUE THREAD

**Issue by ghost** [tsarbuig/WalletHunter#14]
SCENARIO: 
——————
* If the user follows sniper wallets, we often run into the issue where the SALES TAX is huge (>90% sometimes). 

* Usually after some time (30 minutes - 45 minutes), the tax is altered and it drops down to a reasonable level (like 5%). This is because the contract owner has not yet renounced the contract and is able to make changes to the tax settings. 

* After the coin trading well, usually they keep the tax at normal range and then finally reounce the contract. 

* (I believe this is done to prevent bots from pumping and dumping the coin).

Now if the user is utilizing the “autosell mode” and, for example, set his TAKE PROFIT at 200%, it’s very possible that he might buy very low and only to sell on the first spike at 90% tax. 

I realize that there is a feature to check for taxes and avoid purchasing a coin if the tax is too high. That’s awesome, but:

* in the scenario above, this would prevent us from buying a coin with excessive initial tax that will drop its sell tax to reasonable levels in 30 minutes or so. 

* I missed out on a lot of well-performing coins because the sell tax was too high at the time of launch. 

NEW FEATURE SUGGESTION:
————————————————
To avoid this situation, I would like to propose a new feature where a sale is prevented if the SELL TAX is above a certain percentage.

This new feature would prevent an unfortunate situation where he snipes for cheap and sells at 90% tax.

It would also enable the user to “weather” the few minutes of excessive sales tax and allow him to sell at a profit later. 

Of course an excessive BUY TAX is also not favorable and therefore, I believe that the user should still be able to screen for the excessive buy tax. 

For example:

TAX_CHECK : true

MAX_BUY_TAX : “10%”,   // used if TAX_CHECK = true --> bot won't buy if buy tax > MAX_BUY_TAX

MAX_SELL_TAX: "80%", // used if TAX_CHECK = true --> bot won't buy if sell tax > MAX_SELL_TAX

STOP_SELL_TX_IF_SELL_TAX_EXCESSIVE: “10” // bot won’t sell if sell tax > X%

![idea](https://user-images.githubusercontent.com/97957364/216806723-5e5f85f5-e437-4844-9a19-0b3f7907e149.png)
![1_EXCESSIVE-SELL-TAX](https://user-images.githubusercontent.com/97957364/216806730-c1865dbe-a0de-4cf4-886a-abed25499830.png)
![2_EXCESSIVE-SELL-TAX](https://user-images.githubusercontent.com/97957364/216806731-8490bfe0-922e-48ab-b14e-150a06e63060.png)
![3_EXCESSIVE-SELL-TAX](https://user-images.githubusercontent.com/97957364/216806732-6e55258b-b223-45f3-90a8-c8f326c13914.png)
![4_EXCESSIVE-SELL-TAX](https://user-images.githubusercontent.com/97957364/216806734-86f1c102-388f-498e-92d8-9151a7cfabf3.png)
![5_EXCESSIVE-SELL-TAX](https://user-images.githubusercontent.com/97957364/216806735-679f85d1-df79-4dfa-b047-597c56e80fa8.png)
![6_EXCESSIVE-SELL-TAX](https://user-images.githubusercontent.com/97957364/216806736-3d7569e3-551f-43d9-ac01-ac46b2eedac0.png)

**Comment by AdamB2023** [comment]
`MAX_SELL_TAX` already handling this case for selling as well.
However, if it's really necessary to have it separated for sell, then indeed it would require another variable.

**Comment by PumpyMcShillbo** [comment]
> 

Hi Adam, 

I wasn't aware of this parameter. Is this new?

**Comment by ghost** [comment]
> `MAX_SELL_TAX` already handling this case for selling as well. However, if it's really necessary to have it separated for sell, then indeed it would require another variable.

The problem with that is that MAX_SELL_TAX would ignore this purchase altogether. Again, the sell tax is being manipulated in a lot of these shitcoins for about 30 minutes to 1 hour. So we needed an alternative solution which TsarBuig has implemented in the latest release. I am eager to see it working.

**Comment by AdamB2023** [comment]
From my understanding, you are requesting separated variable for tax check when you already own a coin?
Which kind of alternative solution has been implemented which would address that?

**Comment by ghost** [comment]
> 

The issue is clearly explained in the ticket and evident from the screenshots I have provided. Yes, the tax check is for coins already owned.

**Comment by AdamB2023** [comment]
>  So we needed an alternative solution which TsarBuig has implemented in the latest release.

Which solution / commit / update you mean?

As for now, running trade is handled with `MAX_SELL_TAX `.
Therefore, i propose (i guess same like you) to add `MAX_SELL_TAX_DURING_TRADE` to leave the trade before it will change.
However, as per my another issue https://github.com/tsarbuig/WalletHunter/issues/28 you can see that it may not always work with custom contracts.

**Comment by ghost** [comment]
Latest release bro v0.49.4. Read release notes along with this issue description, I think it will all make sense after that

**Comment by ghost** [comment]
@tsarbuig you've already solved this issue, so I'll close this one
