### ISSUE TITLE
“buy_and_sell” Mode - Need to Add Ability to Retry SELL TX if it Fails 

### ISSUE THREAD

**Issue by ghost** [tsarbuig/WalletHunter#15]
If the tracked wallet’s BUY TX fails, then the tracked wallet will have no coins to sell. 

Hence, there is no "sell signal" in this mode. 

If the tracked wallet's BUY TX fails,  BUT our BUY TX succeeds, then it should convert to "autosell mode" for that TX. Otherwise we will end up with coins that do not get sold and possibly crash in the meantime. 

===============================================

To address this issue, I propose the following solution:

1. After a successful purchase in my wallet, have Wallet Hunter check the tracked wallet's transaction to see if it was also successful.

2. If the tracked wallet's transaction is not successful, have Wallet Hunter enter into the "autosell" mode and sell the coins according to the user's defined take profit targets and stop loss.

If this requires a lot of work, then, at the very least, I think the user should constantly be alerted that this coin has no sell signal & that a manual sell is required.

===============================================

I realize that the new "**buy_and_sell_and_autosell**" mode you created mitigates some of the issue above, but it does not change the fact that the "**buy_and_sell**" mode will not work in this scenario described above.

**Comment by tsarbuig** [comment]
I don't understand why the "buy_and_sell_and_autosell" mode does not solve this ?

**Comment by ghost** [comment]
Because if someone uses the **"buy_and_sell" mode** in this situation, then it will not have a sell signal. 

The user should be made aware the there is no sell signal and that a manual sell is now required. 

I feel that there should at least be a RED warning that keeps repeating in the output (much like the autosell price updates do currently). This will alert the user that something went wrong and allow them to take proper & timely action.

**Comment by tsarbuig** [comment]
Added a new Warning message if WalletHunter did not succeed to sell a token. This warning message will be displayed every 60s, and auto-disappear if you sell token manually :
