### ISSUE TITLE
If SELL TX FAILS, WH needs to Retry Selling Repeatedly

### ISSUE THREAD

**Issue by ghost** [tsarbuig/WalletHunter#16]
When WH attempts to sell a coin and the SELL TX **fails**, it simply stops trying to sell it. This can be a costly mistake. 

Therefore, I think we need WH to **repeatedly attempt to sell after a sell failure**. 

This feature is already available in LimitSwap and can be set with MAX_FAILED_TX_IN_A_ROW.

**Comment by tsarbuig** [comment]
already exist since last version

**Comment by ghost** [comment]
Thank you - sorry I didn't realize.

**Comment by AdamB2023** [comment]
The formula seems to be a bit complicated now.
Couldn't it sum up, instead of multiply and sum?
Ex. 15 + 30, not 15+15*30.
Or it could even be a static number set,
This way we can easier set exact retry slippage, otherwise we always have to calculate manually the output.

**Comment by ghost** [comment]
> 

Hi Adam, 

I was confused by this as well. I ignored it because I wonder is there is a particular reason why TsarBuig did it this way.

Either way, I think this issue needs its own ticket because it's a little different from what I reported above.

**Comment by AdamB2023** [comment]
Hi! You requested a sell repeat in case of failure.
This is already available, however could be improved.
Here are my suggestions: 

1. `AUTO_RETRY_AFTER_SELL_TX_FAIL` - we can only set to `true` or `false`, instead could be a number of retries.
2. `ADDITIONAL_SLIPPAGE_FOR_AUTO_RETRY_SELL` - i have two ideas for this value:

Idea 1
`ADDITIONAL_SLIPPAGE_FOR_SELL : "10%"`
`ADDITIONAL_SLIPPAGE_FOR_AUTO_RETRY_SELL : "5%"`
1 retry - 10+5% = 15%
2 retry - 10+2*5% = 20%
3 retry - 10+3*5% = 25%

Idea 2
`ADDITIONAL_SLIPPAGE_FOR_SELL : "10%"`
`ADDITIONAL_SLIPPAGE_FOR_AUTO_RETRY_SELL : "5%"`
All retries - 10+5% = 15%

@PumpyMcShillbo what's your opinion on that?
