### ISSUE TITLE
[Feature] Sell retry on failure

### ISSUE THREAD

**Issue by AdamB2023** [tsarbuig/WalletHunter#2]
Sometimes, when price changes too much, we end up with `Fail with error 'UniswapV2Router: INSUFFICIENT_OUTPUT_AMOUNT€'`.
This force us to either sell manually, or wait on the price pullback, which is pretty uncommon in some cases.
It would be helpful to have an `SELL_RETRY_ON_FAILURE` option, which would immediately retry sell on failure.
Either a single sell, or the amount of possible attempts could be specified as a parameter.

**Comment by tsarbuig** [comment]
hello bro, that's a great suggestion
But what should I change, precisely, between first Tx and retry ? Increase slippage by 20% ? Put unlimited slippage ? 
Thanks :)

**Comment by AdamB2023** [comment]
It depends on what we can do.
Maybe one of these:
1. Check market price and add 10% slippage; or
2. allow user to define slippage for TX retry

**Comment by AdamB2023** [comment]
https://github.com/tsarbuig/WalletHunter/releases/tag/v0.49.2
Thanks!
