### ISSUE TITLE
“buy_and_sell_and_autosell” mode - clarification on Tx_GAS_FOR_SELL

### ISSUE THREAD

**Issue by ghost** [tsarbuig/WalletHunter#21]
Let's assume: `Tx_GAS_FOR_SELL: '130%'`

Normally, in **“buy_and_sell”** mode this would take the tracked wallet’s gas * 130%

But in **“buy_and_sell_and_autosell”** mode, if the sell happens through an “autosell”, what gas does it use to calculate that? 

I think “BOOST” would work better for an autosell because it takes market gas * PERCENTAGE. 

But the problem is we don’t know if the sale will be triggered by (A) the tracked wallet or (B) an autosell.

How do we solve this problem?

![IMAGE 2023-02-05 21:54:24](https://user-images.githubusercontent.com/97957364/216880284-d8bd2d85-7946-4e1d-82fd-12ebae3e86bf.jpg)

**Comment by AdamB2023** [comment]
Yes, for autosell and autobuy it should use GAS_BOOST_FOR_BUY / SELL in general.
@tsarbuig How it's currently working?
I believe I faced an issue with that today, as bot chooses too low gas.

**Comment by tsarbuig** [comment]
- if it clones a SELL tx , it will use Gas = 130%
- it it makes an autosell, it will use BOOST + 25% 

;)

**Comment by ghost** [comment]
Great news! Ok so is it always 25% boost? Or will it follow GAS_BOOST_FOR_SELL?
