### ISSUE TITLE
Missing TXs in logs

### ISSUE THREAD

**Issue by ghost** [tsarbuig/WalletHunter#22]
I have observed that certain coins purchased by tracked wallet are not appearing in the my logs (or even output in the terminal).

Normally, WH would either copy the purchase or print a reason why we cannot purchase it. 

In this case, there is no record of these coins in the logs or screen output. 

It is as if these purchases were not registered or "seen" by WH. 

======================================================

The coins that were purchased but did not show up in the logs were: 

$ETHGI
https://etherscan.io/address/0x0cdcccdfdded233e29113959833a2793be0be9fa

$SCOUT
https://etherscan.io/address/0xd0e48f71fbc5c2358e0d30d991985bf7392d9824

![IMAGE 2023-02-05 22:27:16](https://user-images.githubusercontent.com/97957364/216883683-b8daec2e-6b3b-4205-b7fa-adc0560df83f.jpg)

![IMAGE 2023-02-05 22:27:25](https://user-images.githubusercontent.com/97957364/216883697-5d57f3ed-0e2c-4195-aeaa-bebbb93726bf.jpg)

**Comment by ghost** [comment]
I have sent you the logs via telegram

**Comment by AdamB2023** [comment]
Afaik, if you can't see TX in WH log = it wasn't provided to WH, as it's printing all received TX.

I've been facing it for quite a long time.
Today, after a week of testing, I'm almost sure that this is a node issue.
@PumpyMcShillbo are you using remote ws node?

**Comment by ghost** [comment]
yes I'm using a remote node and connect locally via WS

**Comment by AdamB2023** [comment]
I would advise you to get a local node on your dedicated server, where you will deploy WH as well.
I'm almost sure this is the reason of the issue, as WH is printing all TX received from node.
For me, doing so immediately fixed this missing TX.

**Comment by ghost** [comment]
I'm running an ETH node on Hetzner. My WH is running on the same server and connected with WS locally (127.0.0.1)

**Comment by AdamB2023** [comment]
If you are running a local node, the only thought i have is that the wallet you is not always using a public mempool.
Sometimes you can see a label for that on etherscan.

**Comment by ghost** [comment]
Why would that be the case? Can you explain this random occurrence?

**Comment by AdamB2023** [comment]
The wallet you track may randomly use non public mempool with nodes like FlashBots.
Their purpose is to avoid being copied, sometimes they do that for buy, sometimes for sell.
It's usually later labeled on Etherscan, but not always.
If there's no TX visible for tracked wallet in WalletHunter, it means node didn't received it, and WalletHunter can't do anything.

**Comment by ghost** [comment]
Thanks that's interesting info!

**Comment by tsarbuig** [comment]
+1 if it does not appear on WalletHunter, it means that this Tx was sent through Flashbots RPC. Etherscan usually display it in upper-left corner, but sometimes it does not

https://www.youtube.com/watch?v=0WVEySikzo4&themeRefresh=1
watch this for more info

I'm not a node expert, but I've always wondered if there is a way to put your node in DEBUG mode, and trace in logs every TxHash that it sent to WalletHunter ? 

So as to be 100% sure it's a node problem...
