### ISSUE TITLE
[Feature] Custom labels for addresses

### ISSUE THREAD

**Issue by AdamB2023** [tsarbuig/WalletHunter#23]
While tracking many addresses, it would be helpful to add labels to them.

Config file:
```
TRACKED_WALLET : [
"0xBaF6dC2E647aeb6F510f9e318856A1BCd66C5e19;NAME1",
"0x5a8216a9c47ee2E8Df1c874252fDEe467215C25b;NAME2",
"0x127D736495CCABe6433C62BdDdDF04bf36d411E2;NAME3"
```
Console:
![cns](https://user-images.githubusercontent.com/114318928/217029137-10deeacf-8b13-478b-8354-00783d4e3c51.png)

**Comment by tsarbuig** [comment]
I know this would be handy, but I'm afraid users could make some typos and create bugs...

it this really super mega important or can you lean with it ? :)

**Comment by AdamB2023** [comment]
I made an WEB UI for my custom view purposes 😀
Closing this one, will be worth considering if there will be more similar requests.
