### ISSUE TITLE
[REQUEST] cooldown blocks for WH

### ISSUE THREAD

**Issue by iragoiko** [tsarbuig/WalletHunter#48]
Functions which act as wait time since buy block until finally activates autosell functions.

COOLDOWN BLOCKS = 3

It should wait 3 entire blocks (since buy block) to activate autosells.

By default, set it to 0.

**Comment by tsarbuig** [comment]
done : AUTOSELL_COOLDOWN_BLOCKS hidden option in v0.50.0
