### ISSUE TITLE
[Improvement] Faster start for ANTI RUG

### ISSUE THREAD

**Issue by AdamB2023** [tsarbuig/WalletHunter#51]
v0.50.0

I assume Anti Rug upon start is doing an API call.
Even with entered `EXPLORER_API_KEY`, it took 3s for 5 calls instead of 1s.

```
-- ANTI RUG ----------------------------------------------------
02-19 02:51:12.5112  919e - ANTI RUG ------------- 
02-19 02:51:12.5112  919e - GET CONTRACT --------- 
02-19 02:51:12.5112  6427 - ANTI RUG ------------- 
02-19 02:51:13.5113  6427 - GET CONTRACT --------- 
02-19 02:51:13.5113  637d - ANTI RUG ------------- 
02-19 02:51:14.5114  637d - GET CONTRACT --------- 
02-19 02:51:14.5114  8f65 - ANTI RUG ------------- 
02-19 02:51:14.5114  8f65 - GET CONTRACT --------- 
02-19 02:51:14.5114  26f3 - ANTI RUG ------------- 
02-19 02:51:15.5115  26f3 - GET CONTRACT --------- 
```

**Comment by tsarbuig** [comment]
nobody complained

**Comment by AdamB2023** [comment]
I get it that nobody complained, however, target of every application should be also performance.
The calls aren't done in parallel / multithread, otherwise all would be sent/returned almost immediately.
For a frequent copy-trading, it's an issue, as trade may happen during extended rug-check.
