### ISSUE TITLE
[Feature] Blacklist only for buy

### ISSUE THREAD

**Issue by AdamB2023** [tsarbuig/WalletHunter#54]
As currently it's not possible to define time for storing bought coins, WH is buying them again if midnight passes.
However, if i blacklist them manually, it also blacklist selling them.

Could you add a switch like `BLACKLIST_ONLY_FOR_BUY` with `true` / `false`?

**Comment by tsarbuig** [comment]
good suggestion : shouldn't I make it the default behaviour ? What do you think ?

**Comment by AdamB2023** [comment]
`BLACKLIST_ONLY_FOR_BUY` could indeed be set to `true` by default.
However, a separated blacklist for buy and sell would be best.

Why it may be useful?
1. There may be some coins which we know are scam / old, and we don't want to copy
2. User may want to have some coins on his wallet, which he don't want to be sold

**Comment by tsarbuig** [comment]
I could do it easily, of course, but there are already soooo many parameters... I want to keep it not too much 

--> set it for BUY only in v0.50.2b
