### ISSUE TITLE
WH Transaction Log - Missing SELL Info

### ISSUE THREAD

**Issue by ghost** [tsarbuig/WalletHunter#60]
As you can see in this screenshot, the coin "RC" (Rekt City) was bought and sold.

![SCR-20230221-rt2](https://user-images.githubusercontent.com/97957364/220502894-dc3fe520-0e13-48e7-95cb-ae2e6a952a77.png)

However, the sale info is missing in the TX LOG:

![SCR-20230221-rua](https://user-images.githubusercontent.com/97957364/220502914-c9e892c9-eb3a-4cd7-9d52-75c25aea41e6.png)

I think what happened is that we crossed over to a new day and the next day's TX LOG file was created. But it is empty:

![SCR-20230221-rxj](https://user-images.githubusercontent.com/97957364/220502416-6fdceaa2-fe68-4a38-aa0b-717233129b08.png)

I will DM you the log files in telegram

**Comment by tsarbuig** [comment]
You're right, that was the reason of this error. 
Bot will now ALSO check in yesterday file
