### ISSUE TITLE
[Feature] Anti trap protection

### ISSUE THREAD

**Issue by iragoiko** [tsarbuig/WalletHunter#61]
Request for new feature

> Block xxx0
> Hunted wallet #1: sends buy tx 1 (gas 25)
> Wh: buy tx 1 (gas 25)

> Same block xxx0 **(new feature)**
> Hunted wallet #1: send 0 eth value funds to his wallet with more gas (gas 25+10). Result previous buy tx has been replaced/cancelled
> **Wh: should also send 0 eth value to wh wallet (gas 25+10)**

I see, with this method some hunted wallets are guiding their followers to scam tokens. To prevent that would be nice that WH gets ability to cancel/replace buy tx in the same block.

**Comment by tsarbuig** [comment]
Done
