### ISSUE TITLE
[Improvement] Check market Gas price for MAX_GAS_FOR_ANTIRUG

### ISSUE THREAD

**Issue by tsarbuig** [tsarbuig/WalletHunter#62]
- instead of checking only the MAX price
- when I see such Tx, check current Gas price on the blockchain, and see if it's not too high

and use this market price to check if it won't go higher than your MAX_GAS_FOR_ANTIRUG parameter

**Comment by iragoiko** [comment]
That's great, thanks Tsar for continuous improvement

**Comment by tsarbuig** [comment]
done
